import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class Consts {
  static double defaultPadding = 16;

  static Color primaryColor = const Color.fromRGBO(65, 180, 152, 1);
  static Color secondaryColor = const Color.fromRGBO(119, 209, 149, 1);

  static TextStyle titleTextStyle =
      const TextStyle(fontSize: 35, fontWeight: FontWeight.bold);

  static TextStyle buttonTextStyle =
      TextStyle(fontSize: 17, fontWeight: FontWeight.bold, color: Colors.white);
  static TextStyle defaultTextStyle =
      TextStyle(fontWeight: FontWeight.bold, fontSize: 17);
  static String baseUrl = "http://172.16.15.0:8080/api";
  static final List<String> languages = [
    "Afar",
    "Abkhazian",
    "Afrikaans",
    "Akan",
    "Albanian",
    "Amharic",
    "Arabic",
    "Aragonese",
    "Armenian",
    "Assamese",
    "Avaric",
    "Avestan",
    "Aymara",
    "Azerbaijani",
    "Bashkir",
    "Bambara",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bihari",
    "Bislama",
    "Bosnian",
    "Breton",
    "Bulgarian",
    "Burmese",
    "Catalan",
    "Valencian",
    "Chamorro",
    "Chechen",
    "Chichewa",
    "Chewa",
    "Nyanja",
    "Chinese",
    "Chuvash",
    "Cornish",
    "Corsican",
    "Cree",
    "Croatian",
    "Czech",
    "Danish",
    "Divehi",
    "Dhivehi",
    "Maldivian",
    "Dutch",
    "Dzongkha",
    "English",
    "Esperanto",
    "Estonian",
    "Ewe",
    "Faroese",
    "Fijian",
    "Finnish",
    "French",
    "Fulah",
    "Galician",
    "Georgian",
    "German",
    "Greek",
    "Guarani",
    "Gujarati",
    "Haitian",
    "Haitian Creole",
    "Hausa",
    "Hebrew",
    "Herero",
    "Hindi",
    "Hiri Motu",
    "Hungarian",
    "Interlingua",
    "Indonesian",
    "Interlingue",
    "Irish",
    "Igbo",
    "Inupiaq",
    "Ido",
    "Icelandic",
    "Italian",
    "Inuktitut",
    "Japanese",
    "Javanese",
    "Kalaallisut",
    "Greenlandic",
    "Kannada",
    "Kanuri",
    "Kashmiri",
    "Kazakh",
    "Khmer",
    "Kikuyu",
    "Gikuyu",
    "Kinyarwanda",
    "Kirghiz",
    "Kyrgyz",
    "Komi",
    "Kongo",
    "Korean",
    "Kurdish",
    "Kuanyama",
    "Kwanyama",
    "Latin",
    "Luxembourgish",
    "Letzeburgesch",
    "Ganda",
    "Limburgish",
    "Limburger",
    "Limburgan",
    "Lingala",
    "Lao",
    "Lithuanian",
    "Luba-Katanga",
    "Latvian",
    "Manx",
    "Macedonian",
    "Malagasy",
    "Malay",
    "Malayalam",
    "Maltese",
    "Maori",
    "Marathi",
    "Marshallese",
    "Mongolian",
    "Nauru",
    "Navajo",
    "Navaho",
    "Norwegian Bokmål",
    "North Ndebele",
    "Nepali",
    "Ndonga",
    "Norwegian Nynorsk",
    "Norwegian",
    "Nuosu",
    "South Ndebele",
    "Occitan",
    "Ojibwa",
    "Church Slavic",
    "Church Slavonic",
    "Old Church Slavonic",
    "Old Slavonic",
    "Oromo",
    "Oriya",
    "Ossetian",
    "Ossetic",
    "Panjabi",
    "Punjabi",
    "Pali",
    "Persian",
    "Polish",
    "Pashto",
    "Pushto",
    "Portuguese",
    "Quechua",
    "Romansh",
    "Kirundi",
    "Romanian",
    "Russian",
    "Sanskrit",
    "Sardinian",
    "Sindhi",
    "Northern Sami",
    "Samoan",
    "Sango",
    "Serbian",
    "Gaelic",
    "Scottish Gaelic",
    "Shona",
    "Sinhala",
    "Sinhalese",
    "Slovak",
    "Slovenian",
    "Somali",
    "Southern Sotho",
    "Spanish",
    "Castilian",
    "Sundanese",
    "Swahili",
    "Swati",
    "Swedish",
    "Tamil",
    "Telugu",
    "Tajik",
    "Thai",
    "Tigrinya",
    "Tibetan",
    "Turkmen",
    "Tagalog",
    "Tswana",
    "Tonga",
    "Turkish",
    "Tsonga",
    "Tatar",
    "Twi",
    "Tahitian",
    "Uighur",
    "Uyghur",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Venda",
    "Vietnamese",
    "Volapük",
    "Walloon",
    "Welsh",
    "Wolof",
    "Western Frisian",
    "Xhosa",
    "Yiddish",
    "Yoruba",
    "Zhuang",
    "Chuang",
    "Zulu"
  ];
}
